#:schema ../node_modules/wrangler/config-schema.json

name = "duty-list-api"
main = "index.ts"
compatibility_date = "2024-09-09"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "duty-list"
database_id = "e984ed72-e287-43fa-b39f-8283e025212c"
