#:schema ../node_modules/wrangler/config-schema.json

name = "duty-list-api"
main = "index.ts"
compatibility_date = "2024-09-09"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "duty-list"
database_id ="ec9809c8-b7bb-4212-b10c-ed713815ff3b"
